
mountTopbar('admin');
function showPane(id){$$('.admin-pane,.admin-tab').forEach(x=>x.classList.remove('active'));$('#pane-'+id).classList.add('active');$(`.admin-tab[data-pane="${id}"]`).classList.add('active');loadPane(id)}
$$('.admin-tab').forEach(b=>b.onclick=()=>showPane(b.dataset.pane));
async function loadTargets(){const d=await loadCore(),m=$('#targetMonth').value||ym();for(const t of ['3X','2X','STS']){const v=d.t.find(x=>x.ups_type===t&&monthOf(x.month_start)===m)?.target||0;$('#tg'+t.replace('X','x').toLowerCase()).value=v}}
async function saveTargets(){const m=$('#targetMonth').value+'-01',rows=[['3X','#tg3x'],['2X','#tg2x'],['STS','#tgsts']].map(([ups_type,id])=>({month_start:m,ups_type,target:Number($(id).value)||0}));const r=await sb.from('tqr_monthly_targets').upsert(rows,{onConflict:'month_start,ups_type'});showToast(r.error?r.error.message:'Targets saved')}
async function loadSerials(){const d=await table('tqr_serial_counters');$('#serials').innerHTML=d.map(x=>`<div class="admin-tile"><h3>${x.ups_type}</h3><label>Next Serial<input id="s_${x.ups_type}" type="number" value="${x.next_number}"></label><br><button onclick="saveSerial('${x.ups_type}')">Save</button></div>`).join('')}
async function saveSerial(t){const v=Number($('#s_'+t).value);const r=await sb.from('tqr_serial_counters').update({next_number:v}).eq('ups_type',t);showToast(r.error?r.error.message:'Serial counter saved')}
async function loadEngineers(){const d=await table('tqr_engineers');$('#engineerTable').innerHTML=d.map(e=>`<tr><td>${esc(e.engineer_name)}</td><td>${esc(e.employee_id||'—')}</td><td><button onclick="toggleEngineer('${e.id}',${!e.active})">${e.active?'ACTIVE':'INACTIVE'}</button></td></tr>`).join('')}
async function addEngineer(){const engineer_name=$('#engName').value.trim(),employee_id=$('#engId').value.trim();if(!engineer_name)return;const r=await sb.from('tqr_engineers').upsert({engineer_name,employee_id,active:true},{onConflict:'engineer_name'});showToast(r.error?r.error.message:'Engineer saved');loadEngineers()}
async function toggleEngineer(id,active){await sb.from('tqr_engineers').update({active}).eq('id',id);loadEngineers()}
async function loadTimers(){const t=await getTimers();$('#coreTimer').value=t.core_heatrun_seconds;$('#boostTimer').value=t.booster_heatrun_seconds;$('#stsTimer').value=t.sts_heatrun_seconds}
async function saveTimers(){const rows=[['core_heatrun_seconds','#coreTimer'],['booster_heatrun_seconds','#boostTimer'],['sts_heatrun_seconds','#stsTimer']].map(([setting_key,id])=>({setting_key,setting_value:Number($(id).value)||0}));const r=await sb.from('tqr_settings').upsert(rows,{onConflict:'setting_key'});showToast(r.error?r.error.message:'Timers saved')}
async function loadHistory(){const d=await loadCore(),term=$('#historySearch').value.trim().toLowerCase();let rows=[...d.h].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(term)rows=rows.filter(h=>{const u=d.u.find(x=>x.id===h.unit_id);return [u?.serial_number,u?.qr_code,h.stage,h.engineer_name].some(v=>String(v||'').toLowerCase().includes(term))});$('#historyBody').innerHTML=rows.slice(0,100).map(h=>{const u=d.u.find(x=>x.id===h.unit_id);return `<tr><td>${new Date(h.created_at).toLocaleString()}</td><td>${esc(u?.serial_number||u?.qr_code)}</td><td>${esc(h.stage)}</td><td>${esc(h.engineer_name||'—')}</td><td>${esc(h.result||'')}</td></tr>`}).join('')}
async function loadPane(id){({targets:loadTargets,serials:loadSerials,engineers:loadEngineers,timers:loadTimers,history:loadHistory}[id]||(()=>{}))()}
$('#targetMonth').value=ym();$('#targetMonth').onchange=loadTargets;$('#saveTargets').onclick=saveTargets;$('#addEngineer').onclick=addEngineer;$('#saveTimers').onclick=saveTimers;$('#searchHistory').onclick=loadHistory;
Object.assign(window,{saveSerial,toggleEngineer});
showPane('targets');
