const sb=supabase.createClient(TQR_CONFIG.SUPABASE_URL,TQR_CONFIG.SUPABASE_KEY);const $=s=>document.querySelector(s);let current=null;
const toast=m=>{let t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2500)};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active');if(b.dataset.page==='stock')loadStock();if(b.dataset.page==='active')loadActive()});$('#refresh').onclick=refresh;$('#loadQr').onclick=openQR;$('#qr').addEventListener('keydown',e=>{if(e.key==='Enter')openQR()});
function ym(d=new Date()){return d.toISOString().slice(0,7)};$('#month').value=ym();$('#month').onchange=refresh;
async function data(){let [{data:u},{data:t},{data:b},{data:o}]=await Promise.all([sb.from('tqr_units').select('*'),sb.from('tqr_monthly_targets').select('*'),sb.from('tqr_bays').select('*').eq('active',true),sb.from('tqr_bay_occupancy').select('*,tqr_units(*),tqr_bays(*)').is('released_at',null)]);return{u:u||[],t:t||[],b:b||[],o:o||[]}}
async function refresh(){let d=await data(),now=new Date(),m=ym(now),sel=$('#month').value||m;renderKpi(d,m);renderProgress(d,sel);renderToday(d,now);renderBays(d)}
function monthOf(x){return x?x.slice(0,7):''}function counts(d,type,m){let a=d.u.filter(x=>x.ups_type===type),target=d.t.find(x=>x.ups_type===type&&monthOf(x.month_start)===m)?.target||0;return{target,received:a.filter(x=>monthOf(x.received_at)===m).length,completed:a.filter(x=>x.status==='COMPLETED'&&monthOf(x.completed_at)===m).length,under:a.filter(x=>x.status==='UNDER_TESTING').length,stock:a.filter(x=>x.status==='STOCK').length}}
function renderKpi(d,m){$('#kpis').innerHTML=['3X','2X','STS'].map(type=>{let c=counts(d,type,m),p=c.target?Math.min(100,Math.round(c.completed/c.target*100)):0,cls=type==='3X'?'kpi3x':type==='2X'?'kpi2x':'kpists';return `<div class="kpi ${cls}"><div class="kpi-top"><div><h1>${type}</h1><div class="kpi-sub">TRINERGY ${type==='STS'?'STS':type==='3X'?'T3X':'T2X'}</div></div><div class="ring" style="--p:${p}"><div><b>${p}%</b><small>Completed</small></div></div><div class="ups-art ${type.toLowerCase()}"><span></span><span></span><span></span></div></div><div class="stats"><div class="stat target"><i>🎯</i><span>Target</span><b>${c.target}</b></div><div class="stat received"><i>▣</i><span>Received</span><b>${c.received}</b></div><div class="stat completed"><i>✓</i><span>Completed</span><b>${c.completed}</b></div><div class="stat testing"><i>⚙</i><span>Under Testing</span><b>${c.under}</b></div><div class="stat stock"><i>◆</i><span>Stock</span><b>${c.stock}</b></div></div></div>`}).join('')}
function renderProgress(d,m){$('#progress').innerHTML=['3X','2X','STS'].map(type=>{let c=counts(d,type,m),p=c.target?Math.min(100,Math.round(c.completed/c.target*100)):0;return `<div class="progrow"><b class="progtype">${type}</b><div class="progresswrap"><div class="progressvalues"><span>Completed <strong>${c.completed}</strong></span><span>Target <strong>${c.target}</strong></span></div><div class="track"><div class="fill" style="width:${p}%"></div></div></div><div class="finishflag" title="Target finish">🏁</div></div>`}).join('')}
function renderToday(d,now){let day=now.toISOString().slice(0,10);$('#today').innerHTML='<div class="today-title">▣ &nbsp;Today\'s Status <span>'+now.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})+'</span></div><table class="todaytable"><tr><th>Type</th><th class="c-received">Received</th><th class="c-completed">Completed</th><th class="c-testing">Under Testing</th><th class="c-stock">Stock</th></tr>'+['3X','2X','STS'].map(t=>`<tr><th>${t}</th><td class="c-received">${d.u.filter(x=>x.ups_type===t&&x.received_at?.slice(0,10)===day).length}</td><td class="c-completed">${d.u.filter(x=>x.ups_type===t&&x.completed_at?.slice(0,10)===day).length}</td><td class="c-testing">${d.u.filter(x=>x.ups_type===t&&x.status==='UNDER_TESTING').length}</td><td class="c-stock">${d.u.filter(x=>x.ups_type===t&&x.status==='STOCK').length}</td></tr>`).join('')+'</table>'}
function renderBays(d){$('#bays').innerHTML=d.b.map(b=>{let slots=b.bay_kind==='CORE'?['LV','HV']:[b.bay_kind==='STS_TEST'?'STS_TEST':'STS_HEATRUN'];return `<div class="bay"><h4>● ${esc(b.bay_name)}</h4><div class="sections">${slots.map(s=>{let o=d.o.find(x=>x.bay_id===b.id&&x.section===s),u=o?.tqr_units;return `<div class="slot ${u?'':'empty'}"><strong>${s.replace('_',' ')}</strong>${u?`<h3>${esc(u.serial_number?.slice(-4)||'----')} <small>${u.ups_type}</small></h3><div>${esc(u.current_stage)}</div>`:'Available'}</div>`}).join('')}</div></div>`}).join('')}
async function openQR(){let q=$('#qr').value.trim();if(!q)return;let {data}=await sb.from('tqr_units').select('*,tqr_stage_state(*)').eq('qr_code',q).maybeSingle();current=data;if(!data)return renderNew(q);renderUnit(data)}
function renderNew(q){$('#unitbox').innerHTML=`<div class="card"><h3>New QR: ${esc(q)}</h3><p>First scan = Received only. Select type:</p><div class="types">${['3X','2X','STS'].map(t=>`<button onclick="receive('${t}')">${t}</button>`).join('')}</div></div>`}
window.receive=async type=>{let q=$('#qr').value.trim(),{error}=await sb.from('tqr_units').insert({qr_code:q,ups_type:type,current_stage:'RECEIVED'});if(error)return toast(error.message);toast(type+' Received');openQR();refresh()}
async function reloadUnit(){let {data}=await sb.from('tqr_units').select('*,tqr_stage_state(*)').eq('id',current.id).single();current=data;renderUnit(data);refresh()}
function st(u){return Array.isArray(u.tqr_stage_state)?u.tqr_stage_state[0]:u.tqr_stage_state}
function renderUnit(u){let s=st(u)||{},html=`<div class="card"><h3>${u.serial_number||'Serial not assigned'} · ${u.ups_type}</h3><p>Status: <b>${u.status}</b> · Stage: <b>${esc(u.current_stage)}</b></p><div class="actions">`;
if(u.status==='RECEIVED')html+=`<button onclick="bindSerial()">Assign Serial</button>`;
if(u.serial_number&&u.status==='RECEIVED')html+=`<button onclick="startLV()">Select Bay + Start LV</button>`;
if(u.status==='UNDER_TESTING'){if(!s.hipot_passed)html+=`<button onclick="hipot()">Hi-Pot (LV + Hi-Pot PASS)</button>`;if(s.hipot_passed&&!s.hv_started)html+=`<button onclick="startHV()">HV Testing In Progress + Select Bay</button>`;if(s.hv_started&&!s.hv_passed)html+=`<button class="pass" onclick="hvPass()">HV PASSED</button>`;if(s.hv_started&&!s.core_heatrun_started)html+=`<button class="warn" onclick="heatStart('core')">Start Core Heatrun</button>`;if(s.hv_started&&!s.booster_1_started&&u.ups_type!=='STS')html+=`<button class="warn" onclick="heatStart('booster_1')">Start Booster 1</button>`;if(s.booster_1_passed&&!s.booster_2_started&&u.ups_type!=='STS')html+=`<button class="warn" onclick="heatStart('booster_2')">Start Booster 2</button>`;if(u.ups_type==='3X'&&s.booster_2_passed&&!s.booster_3_started)html+=`<button class="warn" onclick="heatStart('booster_3')">Start Booster 3</button>`;['core','booster_1','booster_2','booster_3'].forEach(k=>{if(s[k+'_started']&&!s[k+'_passed'])html+=`<button class="pass" onclick="heatPass('${k}')">Check & PASS ${k.replaceAll('_',' ')}</button>`});let heats=s.core_heatrun_passed&&(u.ups_type==='STS'||(s.booster_1_passed&&s.booster_2_passed&&(u.ups_type!=='3X'||s.booster_3_passed)));if(heats&&!s.parameters_480v_saved)html+=`<button onclick="params()">480V / Parameters Saved</button>`;html+=`<button id="finish" class="pass" onclick="exitUnit('COMPLETED')">TO FINISHING</button><button id="stockbtn" onclick="exitUnit('STOCK')">STOCK TRANSFER</button>`}html+='</div></div>';$('#unitbox').innerHTML=html;if(u.status==='UNDER_TESTING')readyButtons()}
window.bindSerial=async()=>{let {data,error}=await sb.rpc('tqr_assign_serial',{p_unit_id:current.id});if(error)return toast(error.message);toast('Serial assigned: '+data);reloadUnit()}
async function chooseCore(section){let {data:b}=await sb.from('tqr_bays').select('*').eq('bay_kind','CORE').eq('active',true),{data:o}=await sb.from('tqr_bay_occupancy').select('*').eq('section',section).is('released_at',null);let free=b.filter(x=>!o.some(y=>y.bay_id===x.id));if(!free.length){toast('No '+section+' bay available');return null}let names=free.map((x,i)=>`${i+1}. ${x.bay_name}`).join('\n'),n=prompt(`Select ${section} bay:\n${names}`,'1'),ix=Number(n)-1;return free[ix]||null}
window.startLV=async()=>{let b=await chooseCore('LV');if(!b)return;let {error}=await sb.from('tqr_bay_occupancy').insert({bay_id:b.id,section:'LV',unit_id:current.id});if(error)return toast(error.message);await sb.from('tqr_units').update({status:'UNDER_TESTING',current_stage:'LV TESTING',testing_started_at:new Date().toISOString()}).eq('id',current.id);reloadUnit()}
window.hipot=async()=>{let now=new Date().toISOString();await sb.from('tqr_stage_state').update({lv_passed:true,lv_passed_at:now,hipot_passed:true,hipot_passed_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HI-POT PASSED'}).eq('id',current.id);await sb.from('tqr_bay_occupancy').update({released_at:now}).eq('unit_id',current.id).eq('section','LV').is('released_at',null);reloadUnit()}
window.startHV=async()=>{let b=await chooseCore('HV');if(!b)return;let now=new Date().toISOString(),{error}=await sb.from('tqr_bay_occupancy').insert({bay_id:b.id,section:'HV',unit_id:current.id});if(error)return toast(error.message);await sb.from('tqr_stage_state').update({hv_started:true,hv_started_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HV IN PROGRESS'}).eq('id',current.id);reloadUnit()}
window.hvPass=async()=>{let now=new Date().toISOString();await sb.from('tqr_stage_state').update({hv_passed:true,hv_passed_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HV PASSED'}).eq('id',current.id);reloadUnit()}
window.heatStart=async k=>{let now=new Date().toISOString(),o={};o[k+'_started']=true;o[k+'_started_at']=now;await sb.from('tqr_stage_state').update(o).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:k.replaceAll('_',' ').toUpperCase()+' HEATRUN'}).eq('id',current.id);toast('Timer started (pilot confirmation mode)');reloadUnit()}
window.heatPass=async k=>{if(!confirm('Timer complete / checks done? Mark '+k.replaceAll('_',' ')+' as PASSED?'))return;let now=new Date().toISOString(),o={};o[k+'_passed']=true;o[k+'_passed_at']=now;await sb.from('tqr_stage_state').update(o).eq('unit_id',current.id);reloadUnit()}
window.params=async()=>{let now=new Date().toISOString();await sb.from('tqr_stage_state').update({parameters_480v_saved:true,parameters_480v_saved_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'480V / PARAMETERS SAVED'}).eq('id',current.id);reloadUnit()}
async function readyButtons(){let {data}=await sb.rpc('tqr_ready_for_exit',{p_unit_id:current.id});let a=$('#finish'),b=$('#stockbtn');if(a)a.disabled=!data;if(b)b.disabled=!data}
window.exitUnit=async status=>{let {data:ok}=await sb.rpc('tqr_ready_for_exit',{p_unit_id:current.id});if(!ok)return toast('All mandatory stages must PASS first');let now=new Date().toISOString();await sb.from('tqr_bay_occupancy').update({released_at:now}).eq('unit_id',current.id).is('released_at',null);let patch=status==='COMPLETED'?{status,current_stage:'TO FINISHING / COMPLETED',completed_at:now}:{status,current_stage:'INTERNAL STOCK',stock_at:now};await sb.from('tqr_units').update(patch).eq('id',current.id);toast(status==='COMPLETED'?'Completed — KPI updated':'Moved to internal stock');reloadUnit()}
async function loadActive(){let {data:u}=await sb.from('tqr_units').select('*').eq('status','UNDER_TESTING').order('testing_started_at',{ascending:false});$('#activelist').innerHTML=u?.length?'<table class="active-table"><tr><th>Serial</th><th>Type</th><th>Current Stage</th><th>Started</th></tr>'+u.map(x=>`<tr><td><b>${esc(x.serial_number||'—')}</b></td><td>${x.ups_type}</td><td>${esc(x.current_stage||'UNDER TESTING')}</td><td>${x.testing_started_at?new Date(x.testing_started_at).toLocaleString():'—'}</td></tr>`).join('')+'</table>':'<div class="placeholder-card">No UPS currently under testing.</div>'}
async function loadStock(){let {data:u}=await sb.from('tqr_units').select('*').eq('status','STOCK').order('stock_at');$('#stocklist').innerHTML=u?.length?'<table><tr><th>Serial</th><th>Type</th><th>Stock Since</th><th></th></tr>'+u.map(x=>`<tr><td>${esc(x.serial_number)}</td><td>${x.ups_type}</td><td>${new Date(x.stock_at).toLocaleString()}</td><td><button class="pass" onclick="stockFinish('${x.id}')">TO FINISHING</button></td></tr>`).join('')+'</table>':'<p>No UPS in internal stock.</p>'}
window.stockFinish=async id=>{let now=new Date().toISOString();await sb.from('tqr_units').update({status:'COMPLETED',current_stage:'TO FINISHING / COMPLETED',completed_at:now}).eq('id',id);toast('Released from stock — KPI updated');loadStock();refresh()}
sb.channel('tqr-live').on('postgres_changes',{event:'*',schema:'public',table:'tqr_units'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'tqr_bay_occupancy'},refresh).subscribe();refresh();
