const sb=supabase.createClient(TQR_CONFIG.SUPABASE_URL,TQR_CONFIG.SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let current=null,timerTicker=null,cache={u:[],t:[],b:[],o:[],h:[],e:[]},currentEngineer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{let t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',3000)};
const nowIso=()=>new Date().toISOString(), ym=d=>(d||new Date()).toISOString().slice(0,7);
$('#month').value=ym(); $('#targetMonth').value=ym();
setInterval(()=>$('#clock').textContent=new Date().toLocaleString(),1000);

const titles={dash:['Dashboard','Live status of UPS testing across all bays and stages'],scan:['Scan / Update','Engineer test control'],active:['Active UPS','All UPS currently under testing'],bayspage:['Test Bay Monitoring','Live physical bay occupancy'],stock:['Stock / Finishing','Internal buffer stock'],adminhome:['Admin','Open the required admin module from here'],targets:['Targets','Monthly production target control'],serials:['Serial Numbers','Automatic serial counter control'],qrgen:['QR Generator','Generate direct-link QR labels'],engineers:['Engineers','Authorized testing engineer master'],stages:['Stages & Timers','Testing stage and timer control'],baymaster:['Test Bay Master','Add and enable test bays'],oldserial:['Old Serial Re-entry','Bring historical units into tracking'],reports:['Reports & Trends','Management summary'],history:['Scan History','Complete UPS audit trail']};
function go(id){$$('nav button,.page').forEach(x=>x.classList.remove('active'));let n=$(`nav button[data-page="${id}"]`);if(n)n.classList.add('active');$('#'+id).classList.add('active');$('#pageTitle').textContent=titles[id][0];$('#pageSub').textContent=titles[id][1];loadPage(id)}
$$('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#refresh').onclick=()=>loadPage($('.page.active').id); $('#month').onchange=refreshDashboard; if($('#inputType')) $('#inputType').onchange=drawInputChart;
async function q(table,select='*'){let r=await sb.from(table).select(select);if(r.error)throw r.error;return r.data||[]}
async function loadCore(){let [u,t,b,o,h,e]=await Promise.all([q('tqr_units'),q('tqr_monthly_targets'),q('tqr_bays'),q('tqr_bay_occupancy'),q('tqr_stage_history'),q('tqr_engineers')]);cache={u,t,b,o:o.filter(x=>!x.released_at),h,e};return cache}
function monthOf(x){return x?.slice(0,7)||''}
function counts(type,m){let a=cache.u.filter(x=>x.ups_type===type),target=cache.t.find(x=>x.ups_type===type&&monthOf(x.month_start)===m)?.target||0;return{target,received:a.filter(x=>monthOf(x.received_at)===m).length,completed:a.filter(x=>x.status==='COMPLETED'&&monthOf(x.completed_at)===m).length,under:a.filter(x=>x.status==='UNDER_TESTING').length,stock:a.filter(x=>x.status==='STOCK').length}}
async function refreshDashboard(){await loadCore();renderKpis();renderProgress();renderToday();renderBays('#bays');renderRecent();drawInputChart()}
function renderKpis(){let m=ym();$('#kpis').innerHTML=['3X','2X','STS'].map(type=>{let c=counts(type,m),p=c.target?Math.min(100,Math.round(c.completed/c.target*100)):0,cls=type==='3X'?'kpi3x':type==='2X'?'kpi2x':'kpists';return `<div class="kpi ${cls}"><div class="kpi-top"><div><h1>${type}</h1><div class="kpi-sub">TRINERGY ${type==='STS'?'STS':type==='3X'?'T3X':'T2X'}</div></div><div class="ring" style="--p:${p}"><div><b>${p}%</b><small>Completed</small></div></div><div class="ups-art"><span></span><span></span><span></span></div></div><div class="stats"><div class="stat target"><i>🎯</i><span>Target</span><b>${c.target}</b></div><div class="stat received"><i>▣</i><span>Received</span><b>${c.received}</b></div><div class="stat completed"><i>✓</i><span>Completed</span><b>${c.completed}</b></div><div class="stat testing"><i>⚙</i><span>Under Testing</span><b>${c.under}</b></div><div class="stat stock"><i>◆</i><span>Stock</span><b>${c.stock}</b></div></div></div>`}).join('')}
function activeOcc(bid,sec){return cache.o.find(x=>x.bay_id===bid&&x.section===sec)}
function unitForOcc(o){return o&&cache.u.find(u=>u.id===o.unit_id)}
function stageState(u){return Array.isArray(u?.tqr_stage_state)?u.tqr_stage_state[0]:u?.tqr_stage_state}
async function timerText(u){if(!u)return'';let s=stageState(u);if(!s)return'';let keys=['core','booster_1','booster_2','booster_3'];let k=keys.find(k=>s[k+'_started']&&!s[k+'_passed']);if(!k)return'';let timers=await getTimers(),dur=k==='core'?(u.ups_type==='STS'?timers.sts_heatrun_seconds:timers.core_heatrun_seconds):timers.booster_heatrun_seconds,start=new Date(s[k+'_started_at']).getTime(),left=Math.max(0,dur-Math.floor((Date.now()-start)/1000));return `⏱ ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}
function slotHtml(sec,u){return `<div class="slot ${u?'':'empty'}"><span class="tag">${sec.replace('_',' ')}</span>${u?`<h4>${esc((u.serial_number||'----').slice(-4))} <small>${u.ups_type}</small></h4><div class="stage">${esc(u.current_stage||'')}</div><div class="timer" data-timer-unit="${u.id}"></div>`:`<h4>Available</h4><div>Ready for assignment</div>`}</div>`}
function renderToday(){let now=new Date(),day=now.toISOString().slice(0,10);$('#today').innerHTML=`<div class="today-title">▣ &nbsp;Today's Status <span>${now.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</span></div><table class="todaytable"><tr><th>Type</th><th class="c-received">Received</th><th class="c-completed">Completed</th><th class="c-testing">Under Testing</th><th class="c-stock">Stock</th></tr>${['3X','2X','STS'].map(t=>`<tr><th>${t}</th><td class="c-received">${cache.u.filter(x=>x.ups_type===t&&x.received_at?.slice(0,10)===day).length}</td><td class="c-completed">${cache.u.filter(x=>x.ups_type===t&&x.completed_at?.slice(0,10)===day).length}</td><td class="c-testing">${cache.u.filter(x=>x.ups_type===t&&x.status==='UNDER_TESTING').length}</td><td class="c-stock">${cache.u.filter(x=>x.ups_type===t&&x.status==='STOCK').length}</td></tr>`).join('')}</table>`}
function renderBays(sel){let el=$(sel);if(!el)return;let bs=cache.b.filter(b=>b.active!==false);el.innerHTML=bs.map(b=>{let secs=b.bay_kind==='CORE'?['LV','HV']:[b.bay_kind==='STS_TEST'?'STS_TEST':'STS_HEATRUN'];return `<div class="bay" data-bay="${b.id}"><h3>${esc(b.bay_name)}</h3><div class="sections">${secs.map(sec=>{let u=unitForOcc(activeOcc(b.id,sec));return `<div class="slot ${u?'occupied':'empty'}" ${u?`data-unit-qr="${esc(u.qr_code)}"`:''}><span class="tag">${sec.replace('_',' ')}</span>${u?`<h4>${esc((u.serial_number||'----').slice(-4))} <small>${u.ups_type}</small></h4><div class="stage">${esc(u.current_stage||'')}</div><div class="timer" data-timer-unit="${u.id}"></div>`:`<h4>Available</h4><div>Ready for assignment</div>`}</div>`}).join('')}</div></div>`}).join('');el.querySelectorAll('[data-unit-qr]').forEach(x=>x.onclick=e=>{e.stopPropagation();openFromList(x.dataset.unitQr)});el.querySelectorAll('[data-bay]').forEach(x=>x.onclick=()=>openBay(x.dataset.bay));updateBayTimers()}
async function updateBayTimers(){for(let el of $$('[data-timer-unit]')){let u=cache.u.find(x=>x.id===el.dataset.timerUnit);el.textContent=await timerText(u)}}
async function openBay(id){go('bayspage');await loadCore();renderBays('#allbays');let b=cache.b.find(x=>x.id===id);if(!b)return;let occ=cache.o.filter(x=>x.bay_id===id),units=occ.map(unitForOcc).filter(Boolean);$('#baydetail').innerHTML=`<div class="panel"><h2>${esc(b.bay_name)} — Detail</h2>${units.length?units.map(u=>`<div class="unitcard"><button class="linkbtn" onclick="openFromList('${esc(u.qr_code)}')">${esc(u.serial_number||u.qr_code)}</button> · ${u.ups_type} · ${esc(u.current_stage)}</div>`).join(''):'<p>Bay currently available.</p>'}</div>`}
function renderRecent(){let h=[...cache.h].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,8);$('#recent').innerHTML=h.map(x=>{let u=cache.u.find(z=>z.id===x.unit_id);return `<div class="recentrow"><span>${new Date(x.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><span>${esc((u?.serial_number||u?.qr_code||'').slice(-4))}</span><span><i class="badge">${esc(x.stage.replaceAll('_',' '))}</i></span><span>${esc(x.engineer_name||'—')}</span></div>`}).join('')||'<p class="muted">No activity yet.</p>'}
function renderProgress(){let m=$('#month').value||ym();$('#progress').innerHTML=['3X','2X','STS'].map(type=>{let c=counts(type,m),p=c.target?Math.min(100,Math.round(c.completed/c.target*100)):0;return `<div class="progrow"><b class="progtype">${type}</b><div class="progresswrap"><div class="progressvalues"><span>Completed <strong>${c.completed}</strong></span><span>Target <strong>${c.target}</strong></span></div><div class="track"><div class="fill" style="width:${p}%"></div></div></div><div class="finishflag" aria-label="finish"></div></div>`}).join('')}
async function getPlanned(){let {data}=await sb.from('tqr_settings').select('*').eq('setting_key','planned_receipt_per_day').maybeSingle();return Number(data?.setting_value)||0}
async function drawInputChart(){let canvas=$('#inputChart');if(!canvas)return;let m=$('#month').value||ym(),type=$('#inputType')?$('#inputType').value:'ALL',plan=await getPlanned(),[Y,M]=m.split('-').map(Number),days=new Date(Y,M,0).getDate(),actual=Array(days).fill(0);cache.u.filter(u=>monthOf(u.received_at)===m&&(type==='ALL'||u.ups_type===type)).forEach(u=>actual[Number(u.received_at.slice(8,10))-1]++);let dpr=devicePixelRatio||1;canvas.width=Math.max(600,canvas.clientWidth)*dpr;canvas.height=240*dpr;let c=canvas.getContext('2d'),W=canvas.width,H=canvas.height,padL=44*dpr,padR=18*dpr,padT=18*dpr,padB=30*dpr,max=Math.max(plan,...actual,5);c.clearRect(0,0,W,H);c.fillStyle='#061827';c.fillRect(0,0,W,H);c.strokeStyle='rgba(101,179,221,.18)';c.lineWidth=1*dpr;for(let gy=0;gy<=max;gy++){let py=padT+(H-padT-padB)*(1-gy/max);c.beginPath();c.moveTo(padL,py);c.lineTo(W-padR,py);c.stroke();c.fillStyle='#8dc7ee';c.font=`${10*dpr}px Arial`;c.fillText(String(gy),6*dpr,py+3*dpr)}let X=i=>days===1?padL:(padL+i/(days-1)*(W-padL-padR)),Yv=v=>padT+(H-padT-padB)*(1-v/max);c.setLineDash([7*dpr,5*dpr]);c.strokeStyle='#48b9ff';c.lineWidth=2*dpr;c.beginPath();for(let i=0;i<days;i++){let py=Yv(plan);i?c.lineTo(X(i),py):c.moveTo(X(i),py)}c.stroke();c.setLineDash([]);c.lineWidth=2.6*dpr;c.strokeStyle='#24e29f';c.beginPath();actual.forEach((v,i)=>{i?c.lineTo(X(i),Yv(v)):c.moveTo(X(i),Yv(v))});c.stroke();actual.forEach((v,i)=>{let px=X(i),py=Yv(v);c.beginPath();c.fillStyle=Math.abs(v-plan)<=1?'#24e29f':'#ff5c72';c.arc(px,py,3.2*dpr,0,Math.PI*2);c.fill()});c.fillStyle='#8dc7ee';c.font=`${10*dpr}px Arial`;let step=Math.ceil(days/15);for(let i=0;i<days;i+=step)c.fillText(String(i+1),X(i)-3*dpr,H-10*dpr);c.fillStyle='#dff5ff';c.font=`${12*dpr}px Arial`;c.fillText(type==='ALL'?'All Types':type, padL, 12*dpr);canvas._daily={actual,plan,m,type};}
$('#dailyTableBtn').onclick=()=>{let d=$('#inputChart')._daily;if(!d)return;let e=$('#dailyTable');e.classList.toggle('hidden');e.innerHTML=`<div class="tablewrap"><table><tr><th>Day</th><th>Type</th><th>Plan</th><th>Actual</th><th>Variance</th></tr>${d.actual.map((v,i)=>`<tr><td>${i+1}</td><td>${d.type}</td><td>${d.plan}</td><td>${v}</td><td>${v-d.plan}</td></tr>`).join('')}</table></div>`}

async function loadActive(){await loadCore();let u=cache.u.filter(x=>x.status==='UNDER_TESTING');$('#activelist').innerHTML=`<div class="tablewrap"><table><tr><th>Serial</th><th>Type</th><th>QR</th><th>Current Stage</th><th>Bay</th><th>Engineer</th></tr>${u.map(x=>{let o=cache.o.find(z=>z.unit_id===x.id),b=cache.b.find(z=>z.id===o?.bay_id),last=[...cache.h].filter(z=>z.unit_id===x.id&&z.engineer_name).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];return `<tr><td><button class="linkbtn" onclick="openFromList('${esc(x.qr_code)}')">${esc(x.serial_number||'Assigning…')}</button></td><td>${x.ups_type}</td><td>${esc(x.qr_code)}</td><td>${esc(x.current_stage)}</td><td>${esc(b?.bay_name||'—')} ${o?.section||''}</td><td>${esc(last?.engineer_name||'—')}</td></tr>`}).join('')}</table></div>`}
window.openFromList=q=>{go('scan');$('#qr').value=q;openQR()}
$('#loadQr').onclick=openQR;$('#qr').onkeydown=e=>{if(e.key==='Enter')openQR()}
async function openQR(){let code=$('#qr').value.trim();if(!code)return;let {data,error}=await sb.from('tqr_units').select('*,tqr_stage_state(*)').eq('qr_code',code).maybeSingle();if(error)return toast(error.message);current=data;if(!data)return renderNew(code);renderUnit(data)}
function renderNew(code){$('#unitbox').innerHTML=`<div class="unitcard"><span class="eyebrow">NEW QR</span><h2>${esc(code)}</h2><p>First scan records RECEIVED only. Select UPS type.</p><div class="actions">${['3X','2X','STS'].map(t=>`<button onclick="receive('${t}')">${t}</button>`).join('')}</div></div>`}
window.receive=async type=>{let code=$('#qr').value.trim();let {error}=await sb.from('tqr_units').insert({qr_code:code,ups_type:type,status:'RECEIVED',current_stage:'RECEIVED'});if(error)return toast(error.message);let {data:u}=await sb.from('tqr_units').select('id').eq('qr_code',code).single();await sb.from('tqr_stage_history').insert({unit_id:u.id,action:'RECEIVED',stage:'RECEIVED',result:'PASS'});toast(type+' received');openQR();refreshDashboard()}
async function activeEngineers(){let {data}=await sb.from('tqr_engineers').select('*').eq('active',true).order('engineer_name');return data||[]}
function sstate(u){return Array.isArray(u.tqr_stage_state)?u.tqr_stage_state[0]:u.tqr_stage_state}
function heatDone(s,u){return s?.core_heatrun_passed&&(u.ups_type==='STS'||(s.booster_1_passed&&s.booster_2_passed&&(u.ups_type!=='3X'||s.booster_3_passed)))}
async function renderUnit(u){clearInterval(timerTicker);let s=sstate(u)||{},eng=await activeEngineers(),serial=u.serial_number||'Not assigned yet',steps=[['Received',true],['LV',s.lv_passed],['Hi-Pot',s.hipot_passed],['HV',s.hv_passed],['Heatrun',heatDone(s,u)],['480V',s.parameters_480v_saved],['Finish',u.status==='COMPLETED']];$('#unitbox').innerHTML=`<div class="unitcard"><div class="unithead"><div><span class="eyebrow">${esc(u.qr_code)}</span><div class="serialbig">${esc(serial)} <small>• ${u.ups_type}</small></div><div>${esc(u.current_stage)}</div></div><label>Authorized Engineer<select id="engineerPick"><option value="">Select Engineer</option>${eng.map(e=>`<option value="${e.id}" data-name="${esc(e.engineer_name)}">${esc(e.engineer_name)}${e.employee_id?' · '+esc(e.employee_id):''}</option>`).join('')}</select></label></div><div class="stepper">${steps.map(x=>`<div class="step ${x[1]?'done':''}">${x[1]?'✓ ':''}${x[0]}</div>`).join('')}</div><div id="testActions" class="actions"></div></div>`;$('#engineerPick').onchange=e=>{let op=e.target.selectedOptions[0];currentEngineer=e.target.value?{id:e.target.value,name:op.dataset.name}:null;renderActions(u,s)};renderActions(u,s)}
function needEngineer(){if(!currentEngineer){toast('Select an ACTIVE engineer first');return false}return true}
function renderActions(u,s){let a=[];if(u.status==='RECEIVED')a.push(`<div class="actionbox"><h4>Start Testing</h4><button onclick="startLV()">Assign Serial + Start LV</button></div>`);else if(!s.lv_passed)a.push(`<div class="actionbox"><h4>LV Testing</h4><button class="pass" onclick="hipot()">LV Complete + Hi-Pot PASS</button></div>`);else if(!s.hv_started)a.push(`<div class="actionbox"><h4>HV Testing</h4><button onclick="startHV()">Select HV Bay & Start</button></div>`);else{if(!s.hv_passed)a.push(`<div class="actionbox"><h4>HV Testing</h4><button class="pass" onclick="hvPass()">Mark HV PASSED</button></div>`);a.push(heatBox('core','Core Heatrun',s));if(u.ups_type!=='STS'){a.push(heatBox('booster_1','Booster 1',s));a.push(heatBox('booster_2','Booster 2',s));if(u.ups_type==='3X')a.push(heatBox('booster_3','Booster 3',s))}if(heatDone(s,u)&&!s.parameters_480v_saved)a.push(`<div class="actionbox"><h4>480V / Parameters</h4><button class="pass" onclick="params()">Save / Mark Passed</button></div>`);if(s.parameters_480v_saved)a.push(`<div class="actionbox"><h4>Final Exit</h4><button class="pass" onclick="exitUnit('COMPLETED')">TO FINISHING</button> <button class="warn" onclick="exitUnit('STOCK')">STOCK TRANSFER</button></div>`)}$('#testActions').innerHTML=a.join('');startTimerUi(u,s)}
function heatBox(k,label,s){if(s[k+'_passed'])return `<div class="actionbox"><h4>${label}</h4><b style="color:#42e59d">✓ PASSED</b></div>`;if(!s[k+'_started'])return `<div class="actionbox"><h4>${label}</h4><button onclick="heatStart('${k}')">Start Timer</button></div>`;return `<div class="actionbox timerbox" data-timer="${k}"><h4>${label}</h4><div class="timer-readout">Loading…</div><button class="timer-pass pass" onclick="heatPass('${k}')" disabled>Timer running…</button></div>`}
async function log(action,stage,result='PASS',notes=null){if(!current)return;await sb.from('tqr_stage_history').insert({unit_id:current.id,action,stage,result,engineer_id:currentEngineer?.id||null,engineer_name:currentEngineer?.name||null,notes})}
async function reloadUnit(){let {data}=await sb.from('tqr_units').select('*,tqr_stage_state(*)').eq('id',current.id).single();current=data;await renderUnit(data);refreshDashboard()}
async function chooseCore(section){await loadCore();let free=cache.b.filter(b=>b.active!==false&&b.bay_kind==='CORE'&&!cache.o.some(o=>o.bay_id===b.id&&o.section===section));if(!free.length)return toast('No '+section+' section available');let n=prompt('Select '+section+' bay:\\n'+free.map((b,i)=>`${i+1}. ${b.bay_name}`).join('\\n'),'1'),b=free[Number(n)-1];return b||null}
window.startLV=async()=>{if(!needEngineer())return;let b=await chooseCore('LV');if(!b)return;if(!current.serial_number){let r=await sb.rpc('tqr_assign_serial',{p_unit_id:current.id});if(r.error)return toast(r.error.message)}let now=nowIso(),r=await sb.from('tqr_bay_occupancy').insert({bay_id:b.id,section:'LV',unit_id:current.id});if(r.error)return toast(r.error.message);await sb.from('tqr_units').update({status:'UNDER_TESTING',current_stage:'LV TESTING IN PROGRESS',testing_started_at:now}).eq('id',current.id);await log('START','LV','IN_PROGRESS');reloadUnit()}
window.hipot=async()=>{if(!needEngineer())return;let now=nowIso();await sb.from('tqr_stage_state').update({lv_passed:true,lv_passed_at:now,hipot_passed:true,hipot_passed_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HI-POT PASSED'}).eq('id',current.id);await sb.from('tqr_bay_occupancy').update({released_at:now}).eq('unit_id',current.id).eq('section','LV').is('released_at',null);await log('PASS','LV + HI-POT');reloadUnit()}
window.startHV=async()=>{if(!needEngineer())return;let b=await chooseCore('HV');if(!b)return;let now=nowIso(),r=await sb.from('tqr_bay_occupancy').insert({bay_id:b.id,section:'HV',unit_id:current.id});if(r.error)return toast(r.error.message);await sb.from('tqr_stage_state').update({hv_started:true,hv_started_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HV IN PROGRESS'}).eq('id',current.id);await log('START','HV','IN_PROGRESS');reloadUnit()}
window.hvPass=async()=>{if(!needEngineer())return;let now=nowIso();await sb.from('tqr_stage_state').update({hv_passed:true,hv_passed_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HV PASSED'}).eq('id',current.id);await log('PASS','HV');reloadUnit()}
async function getTimers(){let d={core_heatrun_seconds:120,booster_heatrun_seconds:60,sts_heatrun_seconds:120},{data}=await sb.from('tqr_settings').select('*');(data||[]).forEach(x=>{if(x.setting_key in d)d[x.setting_key]=Number(x.setting_value)});return d}
function duration(k,u,t){return k==='core'?(u.ups_type==='STS'?t.sts_heatrun_seconds:t.core_heatrun_seconds):t.booster_heatrun_seconds}
window.heatStart=async k=>{if(!needEngineer())return;let now=nowIso(),p={};p[k+'_started']=true;p[k+'_started_at']=now;let r=await sb.from('tqr_stage_state').update(p).eq('unit_id',current.id).select();if(r.error)return toast(r.error.message);let label=k==='core'?'CORE HEATRUN':k.replaceAll('_',' ').toUpperCase()+' HEATRUN';await sb.from('tqr_units').update({current_stage:label}).eq('id',current.id);await log('START',label,'IN_PROGRESS');reloadUnit()}
async function startTimerUi(u,s){let t=await getTimers();let tick=()=>$$('.timerbox').forEach(box=>{let k=box.dataset.timer,start=s[k+'_started_at'];if(!start)return;let left=Math.max(0,duration(k,u,t)-Math.floor((Date.now()-new Date(start))/1000)),r=box.querySelector('.timer-readout'),b=box.querySelector('.timer-pass');r.textContent=left?`Remaining ${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`:'Timer Complete — Check UPS';b.disabled=left>0;b.textContent=left?'Timer running…':'Check UPS & Mark Passed'});tick();timerTicker=setInterval(tick,1000)}
window.heatPass=async k=>{if(!needEngineer())return;let s=sstate(current),t=await getTimers(),start=s[k+'_started_at'];if(Date.now()-new Date(start)<duration(k,current,t)*1000)return toast('Timer is still running');let p={};p[k+'_passed']=true;p[k+'_passed_at']=nowIso();await sb.from('tqr_stage_state').update(p).eq('unit_id',current.id);let label=k==='core'?'CORE HEATRUN PASSED':k.replaceAll('_',' ').toUpperCase()+' HEATRUN PASSED';await sb.from('tqr_units').update({current_stage:label}).eq('id',current.id);await log('PASS',label);reloadUnit()}
window.params=async()=>{if(!needEngineer())return;let now=nowIso();await sb.from('tqr_stage_state').update({parameters_480v_saved:true,parameters_480v_saved_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'480V / PARAMETERS SAVED'}).eq('id',current.id);await log('PASS','480V / PARAMETERS');reloadUnit()}
window.exitUnit=async status=>{if(!needEngineer())return;let now=nowIso();await sb.from('tqr_bay_occupancy').update({released_at:now}).eq('unit_id',current.id).is('released_at',null);let p=status==='COMPLETED'?{status,current_stage:'TO FINISHING / COMPLETED',completed_at:now}:{status,current_stage:'INTERNAL STOCK',stock_at:now};await sb.from('tqr_units').update(p).eq('id',current.id);await log('EXIT',status==='COMPLETED'?'TO FINISHING':'STOCK TRANSFER');reloadUnit()}

async function loadStock(){await loadCore();let u=cache.u.filter(x=>x.status==='STOCK');$('#stocklist').innerHTML=`<table><tr><th>Serial</th><th>Type</th><th>Stock In</th><th>Action</th></tr>${u.map(x=>`<tr><td>${esc(x.serial_number)}</td><td>${x.ups_type}</td><td>${new Date(x.stock_at).toLocaleString()}</td><td><button onclick="stockFinish('${x.id}')">To Finishing</button></td></tr>`).join('')}</table>`}
window.stockFinish=async id=>{let now=nowIso();await sb.from('tqr_units').update({status:'COMPLETED',current_stage:'TO FINISHING / COMPLETED',completed_at:now}).eq('id',id);await sb.from('tqr_stage_history').insert({unit_id:id,action:'EXIT',stage:'TO FINISHING FROM STOCK',result:'PASS'});loadStock();toast('Completed')}
async function loadTargets(){await loadCore();let m=$('#targetMonth').value||ym();for(let t of ['3X','2X','STS']){let v=cache.t.find(x=>x.ups_type===t&&monthOf(x.month_start)===m)?.target||0;$('#target'+(t==='3X'?'3x':t==='2X'?'2x':'sts')).value=v}$('#plannedDaily').value=await getPlanned()}
$('#targetMonth').onchange=loadTargets;$('#saveTargets').onclick=async()=>{let m=$('#targetMonth').value+'-01',rows=[['3X','#target3x'],['2X','#target2x'],['STS','#targetsts']].map(([ups_type,id])=>({month_start:m,ups_type,target:Number($(id).value)||0}));let r=await sb.from('tqr_monthly_targets').upsert(rows,{onConflict:'month_start,ups_type'});if(r.error)return toast(r.error.message);await sb.from('tqr_settings').upsert({setting_key:'planned_receipt_per_day',setting_value:Number($('#plannedDaily').value)||0},{onConflict:'setting_key'});toast('Targets saved')}
async function loadSerials(){let {data}=await sb.from('tqr_serial_counters').select('*').order('ups_type');$('#serialControls').innerHTML=(data||[]).map(x=>`<div class="serialbox"><h3>${x.ups_type}</h3><label>Next Serial Number<input id="ser_${x.ups_type.replace('X','x')}" type="number" value="${x.next_number}"></label><p>Preview: <b>${x.ups_type==='3X'?'T3X':x.ups_type==='2X'?'T2X':'TST'}${String(x.next_number).padStart(4,'0')}</b></p><button onclick="saveSerial('${x.ups_type}')">Save Next Serial</button></div>`).join('')}
window.saveSerial=async type=>{let id='#ser_'+type.replace('X','x'),v=Number($(id).value);if(!v)return toast('Enter valid number');let r=await sb.from('tqr_serial_counters').update({next_number:v}).eq('ups_type',type);if(r.error)return toast(r.error.message);toast(type+' next serial saved');loadSerials()}
function generateQrBatch(){let qty=Math.max(1,Math.min(100,Number($('#qrQty').value)||1)),start=Date.now(),box=$('#qrBatch');box.innerHTML='';for(let i=0;i<qty;i++){let code='TQR-'+String(start+i),card=document.createElement('div');card.className='qr-card';card.innerHTML=`<div class="qr-canvas"></div><b>${code}</b>`;box.appendChild(card);new QRCode(card.querySelector('.qr-canvas'),{text:`${location.origin}${location.pathname}?qr=${encodeURIComponent(code)}`,width:150,height:150})}$('#qrBatchInfo').textContent=`Generated ${qty} QR codes. First scan registers Received.`}
$('#generateQr').onclick=generateQrBatch;
async function loadEngineers(){let {data}=await sb.from('tqr_engineers').select('*').order('engineer_name');$('#engineerList').innerHTML=`<table><tr><th>Engineer</th><th>Employee ID</th><th>Active</th></tr>${(data||[]).map(e=>`<tr><td>${esc(e.engineer_name)}</td><td>${esc(e.employee_id||'—')}</td><td><button class="${e.active?'pass':'ghost'}" onclick="toggleEngineer('${e.id}',${!e.active})">${e.active?'ACTIVE':'INACTIVE'}</button></td></tr>`).join('')}</table>`}
$('#addEngineer').onclick=async()=>{let name=$('#engName').value.trim(),employee_id=$('#engId').value.trim();if(!name)return toast('Enter engineer name');let r=await sb.from('tqr_engineers').upsert({engineer_name:name,employee_id,active:true},{onConflict:'engineer_name'});if(r.error)return toast(r.error.message);$('#engName').value='';$('#engId').value='';loadEngineers();toast('Engineer saved')}
window.toggleEngineer=async(id,active)=>{await sb.from('tqr_engineers').update({active}).eq('id',id);loadEngineers()}
async function loadStages(){let {data}=await sb.from('tqr_stage_master').select('*').order('sort_order');$('#stageList').innerHTML=`<table><tr><th>Code</th><th>Name</th><th>Required</th><th>Active</th><th></th></tr>${(data||[]).map(s=>`<tr><td>${s.stage_code}</td><td><input id="sn_${s.stage_code}" value="${esc(s.stage_name)}"></td><td><select id="sr_${s.stage_code}"><option value="true" ${s.required?'selected':''}>Required</option><option value="false" ${!s.required?'selected':''}>Optional</option></select></td><td>${s.active?'ON':'OFF'}</td><td><button onclick="saveStage('${s.stage_code}',${s.active})">Save</button> <button class="ghost" onclick="toggleStage('${s.stage_code}',${!s.active})">${s.active?'Disable':'Enable'}</button></td></tr>`).join('')}</table>`;let t=await getTimers();$('#timerCore').value=t.core_heatrun_seconds;$('#timerBooster').value=t.booster_heatrun_seconds;$('#timerSts').value=t.sts_heatrun_seconds}
$('#saveTimers').onclick=async()=>{let rows=[['core_heatrun_seconds','#timerCore'],['booster_heatrun_seconds','#timerBooster'],['sts_heatrun_seconds','#timerSts']].map(([setting_key,id])=>({setting_key,setting_value:Number($(id).value)}));let r=await sb.from('tqr_settings').upsert(rows,{onConflict:'setting_key'});if(r.error)return toast(r.error.message);toast('Timers saved')}
window.saveStage=async(code,active)=>{await sb.from('tqr_stage_master').update({stage_name:$('#sn_'+code).value,required:$('#sr_'+code).value==='true',active}).eq('stage_code',code);toast('Stage saved');loadStages()}
window.toggleStage=async(code,active)=>{await sb.from('tqr_stage_master').update({active}).eq('stage_code',code);loadStages()}
$('#addStage').onclick=async()=>{let stage_code=$('#newStageCode').value.trim().toUpperCase().replace(/\s+/g,'_'),stage_name=$('#newStageName').value.trim(),required=$('#newStageRequired').value==='true';if(!stage_code||!stage_name)return toast('Enter stage code and name');let r=await sb.from('tqr_stage_master').insert({stage_code,stage_name,required,active:true});if(r.error)return toast(r.error.message);loadStages();toast('Stage added')}
async function loadBayMaster(){let {data}=await sb.from('tqr_bays').select('*').order('bay_name');$('#bayMasterList').innerHTML=`<table><tr><th>Bay</th><th>Role</th><th>Sections</th><th>Status</th></tr>${(data||[]).map(b=>`<tr><td>${esc(b.bay_name)}</td><td>${b.bay_kind}</td><td>${b.bay_kind==='CORE'?'LV + HV':'Single'}</td><td><button onclick="toggleBay('${b.id}',${b.active===false})">${b.active===false?'INACTIVE':'ACTIVE'}</button></td></tr>`).join('')}</table>`}
$('#addBay').onclick=async()=>{let bay_name=$('#bayName').value.trim(),bay_kind=$('#bayKind').value;if(!bay_name)return toast('Enter bay name');let r=await sb.from('tqr_bays').insert({bay_name,bay_kind,active:true});if(r.error)return toast(r.error.message);loadBayMaster();toast('Bay added')}
window.toggleBay=async(id,active)=>{await sb.from('tqr_bays').update({active}).eq('id',id);loadBayMaster()}
$('#saveOldSerial').onclick=async()=>{let serial=$('#oldSerialNo').value.trim();if(!serial)return toast('Serial required');let status=$('#oldStatus').value,received=$('#oldReceived').value?new Date($('#oldReceived').value+'T08:00:00').toISOString():nowIso(),completed=$('#oldCompleted').value?new Date($('#oldCompleted').value+'T17:00:00').toISOString():null,qr='OLD-'+serial;let p={qr_code:qr,serial_number:serial,ups_type:$('#oldType').value,status,current_stage:status==='COMPLETED'?'TO FINISHING / COMPLETED':status,received_at:received};if(status==='COMPLETED')p.completed_at=completed||nowIso();if(status==='STOCK')p.stock_at=completed||nowIso();let r=await sb.from('tqr_units').insert(p);if(r.error)return toast(r.error.message);toast('Old serial added')}
async function loadHistory(){await loadCore();let term=$('#historySearch').value.trim().toLowerCase(),rows=[...cache.h].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(term)rows=rows.filter(h=>{let u=cache.u.find(x=>x.id===h.unit_id);return [u?.serial_number,u?.qr_code,h.stage,h.engineer_name,h.action].some(v=>String(v||'').toLowerCase().includes(term))});$('#historyList').innerHTML=`<table><tr><th>Date / Time</th><th>Serial / QR</th><th>Action</th><th>Stage</th><th>Engineer</th><th>Result</th></tr>${rows.map(h=>{let u=cache.u.find(x=>x.id===h.unit_id);return `<tr><td>${new Date(h.created_at).toLocaleString()}</td><td>${esc(u?.serial_number||u?.qr_code)}</td><td>${esc(h.action)}</td><td>${esc(h.stage)}</td><td>${esc(h.engineer_name||'—')}</td><td>${esc(h.result||'')}</td></tr>`}).join('')}</table>`}
$('#loadHistory').onclick=loadHistory;
async function loadReports(){await loadCore();let year=new Date().getFullYear(),done=cache.u.filter(x=>x.status==='COMPLETED'&&new Date(x.completed_at).getFullYear()===year).length,stock=cache.u.filter(x=>x.status==='STOCK').length,under=cache.u.filter(x=>x.status==='UNDER_TESTING').length;$('#reportCards').innerHTML=[['Completed',done],['Under Testing',under],['Stock',stock],['Live Logs',cache.h.length]].map(x=>`<div class="reportcard"><span>${x[0]}</span><br><strong>${x[1]}</strong></div>`).join('');$('#yearTable').innerHTML=`<table><tr><th>Month</th><th>3X Completed</th><th>2X Completed</th><th>STS Completed</th><th>Total</th></tr>${Array.from({length:12},(_,i)=>{let m=`${year}-${String(i+1).padStart(2,'0')}`,v=['3X','2X','STS'].map(t=>cache.u.filter(x=>x.ups_type===t&&x.status==='COMPLETED'&&monthOf(x.completed_at)===m).length);return `<tr><td>${new Date(year,i).toLocaleString('en',{month:'short'})}</td><td>${v[0]}</td><td>${v[1]}</td><td>${v[2]}</td><td>${v.reduce((a,b)=>a+b,0)}</td></tr>`}).join('')}</table>`}
$('#exportCsv').onclick=async()=>{await loadCore();let rows=[['Serial','Type','QR','Status','Stage','Received','Completed','Stock']].concat(cache.u.map(u=>[u.serial_number||'',u.ups_type,u.qr_code,u.status,u.current_stage,u.received_at||'',u.completed_at||'',u.stock_at||'']));let csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Trinergy_Management_Report.csv';a.click()}
function loadPage(id){({dash:refreshDashboard,active:loadActive,bayspage:async()=>{await loadCore();renderBays('#allbays')},stock:loadStock,adminhome:()=>{},targets:loadTargets,serials:loadSerials,engineers:loadEngineers,stages:loadStages,baymaster:loadBayMaster,reports:loadReports,history:loadHistory}[id]||(()=>{}))()}
sb.channel('tqr-live-v5').on('postgres_changes',{event:'*',schema:'public',table:'tqr_units'},()=>loadPage($('.page.active').id)).on('postgres_changes',{event:'*',schema:'public',table:'tqr_bay_occupancy'},()=>loadPage($('.page.active').id)).on('postgres_changes',{event:'*',schema:'public',table:'tqr_stage_history'},()=>loadPage($('.page.active').id)).subscribe();
(async()=>{await refreshDashboard();let code=new URLSearchParams(location.search).get('qr');if(code){go('scan');$('#qr').value=code;openQR()}})();
