const sb=supabase.createClient(TQR_CONFIG.SUPABASE_URL,TQR_CONFIG.SUPABASE_KEY);
const $=s=>document.querySelector(s);let current=null,timerTicker=null;
const toast=m=>{let t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2600)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nowIso=()=>new Date().toISOString();

document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{
  document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));
  b.classList.add('active');$('#'+b.dataset.page).classList.add('active');
  if(b.dataset.page==='stock')loadStock();
  if(b.dataset.page==='active')loadActive();
  if(b.dataset.page==='admin')loadTimers();
});
$('#refresh').onclick=refresh;$('#loadQr').onclick=openQR;$('#qr').addEventListener('keydown',e=>{if(e.key==='Enter')openQR()});
$('#generateQr').onclick=generateQrBatch;$('#saveTimers').onclick=saveTimers;

function ym(d=new Date()){return d.toISOString().slice(0,7)};$('#month').value=ym();$('#month').onchange=refresh;
async function data(){let [{data:u},{data:t},{data:b},{data:o}]=await Promise.all([
 sb.from('tqr_units').select('*'),sb.from('tqr_monthly_targets').select('*'),
 sb.from('tqr_bays').select('*').eq('active',true),
 sb.from('tqr_bay_occupancy').select('*,tqr_units(*),tqr_bays(*)').is('released_at',null)
]);return{u:u||[],t:t||[],b:b||[],o:o||[]}}
async function refresh(){let d=await data(),now=new Date(),m=ym(now),sel=$('#month').value||m;renderKpi(d,m);renderProgress(d,sel);renderToday(d,now);renderBays(d)}
function monthOf(x){return x?x.slice(0,7):''}
function counts(d,type,m){let a=d.u.filter(x=>x.ups_type===type),target=d.t.find(x=>x.ups_type===type&&monthOf(x.month_start)===m)?.target||0;return{target,received:a.filter(x=>monthOf(x.received_at)===m).length,completed:a.filter(x=>x.status==='COMPLETED'&&monthOf(x.completed_at)===m).length,under:a.filter(x=>x.status==='UNDER_TESTING').length,stock:a.filter(x=>x.status==='STOCK').length}}
function renderKpi(d,m){$('#kpis').innerHTML=['3X','2X','STS'].map(type=>{let c=counts(d,type,m),p=c.target?Math.min(100,Math.round(c.completed/c.target*100)):0,cls=type==='3X'?'kpi3x':type==='2X'?'kpi2x':'kpists';return `<div class="kpi ${cls}"><div class="kpi-top"><div><h1>${type}</h1><div class="kpi-sub">TRINERGY ${type==='STS'?'STS':type==='3X'?'T3X':'T2X'}</div></div><div class="ring" style="--p:${p}"><div><b>${p}%</b><small>Completed</small></div></div><div class="ups-art ${type.toLowerCase()}"><span></span><span></span><span></span></div></div><div class="stats"><div class="stat target"><i>🎯</i><span>Target</span><b>${c.target}</b></div><div class="stat received"><i>▣</i><span>Received</span><b>${c.received}</b></div><div class="stat completed"><i>✓</i><span>Completed</span><b>${c.completed}</b></div><div class="stat testing"><i>⚙</i><span>Under Testing</span><b>${c.under}</b></div><div class="stat stock"><i>◆</i><span>Stock</span><b>${c.stock}</b></div></div></div>`}).join('')}
function flagSvg(){return `<svg viewBox="0 0 64 48" aria-label="Finish flag"><path d="M8 4v40" stroke="currentColor" stroke-width="4"/><path d="M11 6 C25 1 38 13 54 7 L54 29 C39 35 26 22 11 29Z" fill="none" stroke="currentColor" stroke-width="2"/><g fill="currentColor"><path d="M12 7h10v10H12zM32 8h10v10H32zM22 17h10v10H22zM42 17h10v10H42z"/></g></svg>`}
function renderProgress(d,m){$('#progress').innerHTML=['3X','2X','STS'].map(type=>{let c=counts(d,type,m),p=c.target?Math.min(100,Math.round(c.completed/c.target*100)):0;return `<div class="progrow"><b class="progtype">${type}</b><div class="progresswrap"><div class="progressvalues"><span>Completed <strong>${c.completed}</strong></span><span>Target <strong>${c.target}</strong></span></div><div class="track"><div class="fill" style="width:${p}%"></div></div></div><div class="finishflag">${flagSvg()}</div></div>`}).join('')}
function renderToday(d,now){let day=now.toISOString().slice(0,10);$('#today').innerHTML='<div class="today-title">▣ &nbsp;Today\'s Status <span>'+now.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})+'</span></div><table class="todaytable"><tr><th>Type</th><th class="c-received">Received</th><th class="c-completed">Completed</th><th class="c-testing">Under Testing</th><th class="c-stock">Stock</th></tr>'+['3X','2X','STS'].map(t=>`<tr><th>${t}</th><td class="c-received">${d.u.filter(x=>x.ups_type===t&&x.received_at?.slice(0,10)===day).length}</td><td class="c-completed">${d.u.filter(x=>x.ups_type===t&&x.completed_at?.slice(0,10)===day).length}</td><td class="c-testing">${d.u.filter(x=>x.ups_type===t&&x.status==='UNDER_TESTING').length}</td><td class="c-stock">${d.u.filter(x=>x.ups_type===t&&x.status==='STOCK').length}</td></tr>`).join('')+'</table>'}
function renderBays(d){$('#bays').innerHTML=d.b.map(b=>{let slots=b.bay_kind==='CORE'?['LV','HV']:[b.bay_kind==='STS_TEST'?'STS_TEST':'STS_HEATRUN'];return `<div class="bay"><h4>● ${esc(b.bay_name)}</h4><div class="sections">${slots.map(s=>{let o=d.o.find(x=>x.bay_id===b.id&&x.section===s),u=o?.tqr_units;return `<div class="slot ${u?'':'empty'}"><strong>${s.replace('_',' ')}</strong>${u?`<h3>${esc(u.serial_number?.slice(-4)||'----')} <small>${u.ups_type}</small></h3><div>${esc(u.current_stage)}</div>`:'Available'}</div>`}).join('')}</div></div>`}).join('')}

async function openQR(){let q=$('#qr').value.trim();if(!q)return;let {data,error}=await sb.from('tqr_units').select('*,tqr_stage_state(*)').eq('qr_code',q).maybeSingle();if(error)return toast(error.message);current=data;if(!data)return renderNew(q);renderUnit(data)}
function renderNew(q){$('#unitbox').innerHTML=`<div class="card"><h3>New QR: ${esc(q)}</h3><p>First scan = Received only. Select UPS type:</p><div class="types">${['3X','2X','STS'].map(t=>`<button onclick="receive('${t}')">${t}</button>`).join('')}</div></div>`}
window.receive=async type=>{let q=$('#qr').value.trim(),{error}=await sb.from('tqr_units').insert({qr_code:q,ups_type:type,current_stage:'RECEIVED'});if(error)return toast(error.message);await historyByQr(q,'RECEIVED','RECEIVED','PASS');toast(type+' Received');openQR();refresh()}
async function reloadUnit(){let {data}=await sb.from('tqr_units').select('*,tqr_stage_state(*)').eq('id',current.id).single();current=data;renderUnit(data);refresh()}
function st(u){return Array.isArray(u.tqr_stage_state)?u.tqr_stage_state[0]:u.tqr_stage_state}
async function history(action,stage,result='PASS',notes=null){if(!current)return;await sb.from('tqr_stage_history').insert({unit_id:current.id,action,stage,result,notes})}
async function historyByQr(q,action,stage,result){let {data:u}=await sb.from('tqr_units').select('id').eq('qr_code',q).single();if(u)await sb.from('tqr_stage_history').insert({unit_id:u.id,action,stage,result})}

function renderUnit(u){clearInterval(timerTicker);let s=st(u)||{},html=`<div class="card"><h3>${u.serial_number||'Serial not assigned'} · ${u.ups_type}</h3><p>Status: <b>${u.status}</b> · Stage: <b>${esc(u.current_stage)}</b></p><div class="actions">`;
if(u.status==='RECEIVED'&&!u.serial_number)html+=`<div class="serial-entry"><input id="manualSerial" placeholder="Enter UPS serial number" autocomplete="off"><button onclick="bindManualSerial()">Save Serial</button></div>`;
if(u.serial_number&&u.status==='RECEIVED')html+=`<button onclick="startLV()">Select Bay + Start LV</button>`;
if(u.status==='UNDER_TESTING'){
 if(!s.hipot_passed)html+=`<button onclick="hipot()">Hi-Pot (LV + Hi-Pot PASS)</button>`;
 if(s.hipot_passed&&!s.hv_started)html+=`<button onclick="startHV()">HV Testing In Progress + Select Bay</button>`;
 if(s.hv_started&&!s.hv_passed)html+=`<button class="pass" onclick="hvPass()">HV PASSED</button>`;
 if(s.hv_started&&!s.core_heatrun_started)html+=`<button class="warn" onclick="heatStart('core')">Start ${u.ups_type==='STS'?'STS':'Core'} Heatrun</button>`;
 if(s.hv_started&&!s.booster_1_started&&u.ups_type!=='STS')html+=`<button class="warn" onclick="heatStart('booster_1')">Start Booster 1</button>`;
 if(s.booster_1_passed&&!s.booster_2_started&&u.ups_type!=='STS')html+=`<button class="warn" onclick="heatStart('booster_2')">Start Booster 2</button>`;
 if(u.ups_type==='3X'&&s.booster_2_passed&&!s.booster_3_started)html+=`<button class="warn" onclick="heatStart('booster_3')">Start Booster 3</button>`;
 ['core','booster_1','booster_2','booster_3'].forEach(k=>{if(s[k+'_started']&&!s[k+'_passed'])html+=`<div class="timerbox" data-timer="${k}"><b>${k==='core'?(u.ups_type==='STS'?'STS Heatrun':'Core Heatrun'):k.replace('_',' ').toUpperCase()}</b><span class="timer-readout">Checking timer…</span><button class="pass timer-pass" data-key="${k}" onclick="heatPass('${k}')" disabled>Timer running…</button></div>`});
 let heats=s.core_heatrun_passed&&(u.ups_type==='STS'||(s.booster_1_passed&&s.booster_2_passed&&(u.ups_type!=='3X'||s.booster_3_passed)));
 if(heats&&!s.parameters_480v_saved)html+=`<button onclick="params()">480V / Parameters Saved</button>`;
 html+=`<button id="finish" class="pass" onclick="exitUnit('COMPLETED')">TO FINISHING</button><button id="stockbtn" onclick="exitUnit('STOCK')">STOCK TRANSFER</button>`;
}
html+='</div></div>';$('#unitbox').innerHTML=html;if(u.status==='UNDER_TESTING'){readyButtons();startTimerUi(u,s)}}

window.bindManualSerial=async()=>{let inp=$('#manualSerial'),serial=inp?.value.trim();if(!serial)return toast('Enter serial number');if(serial.length<3)return toast('Serial number looks too short');let {data:dup}=await sb.from('tqr_units').select('id').eq('serial_number',serial).maybeSingle();if(dup)return toast('Serial already exists');let {error}=await sb.from('tqr_units').update({serial_number:serial}).eq('id',current.id);if(error)return toast(error.message);await history('SERIAL_BOUND','SERIAL','PASS','Manual pilot serial: '+serial);toast('Serial saved: '+serial);reloadUnit()}

async function chooseCore(section){let {data:b}=await sb.from('tqr_bays').select('*').eq('bay_kind','CORE').eq('active',true),{data:o}=await sb.from('tqr_bay_occupancy').select('*').eq('section',section).is('released_at',null);let free=(b||[]).filter(x=>!(o||[]).some(y=>y.bay_id===x.id));if(!free.length){toast('No '+section+' bay available');return null}let names=free.map((x,i)=>`${i+1}. ${x.bay_name}`).join('\n'),n=prompt(`Select ${section} bay:\n${names}`,'1'),ix=Number(n)-1;return free[ix]||null}
window.startLV=async()=>{let b=await chooseCore('LV');if(!b)return;let {error}=await sb.from('tqr_bay_occupancy').insert({bay_id:b.id,section:'LV',unit_id:current.id});if(error)return toast(error.message);await sb.from('tqr_units').update({status:'UNDER_TESTING',current_stage:'LV TESTING',testing_started_at:nowIso()}).eq('id',current.id);await history('START','LV','IN_PROGRESS');reloadUnit()}
window.hipot=async()=>{let now=nowIso();await sb.from('tqr_stage_state').update({lv_passed:true,lv_passed_at:now,hipot_passed:true,hipot_passed_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HI-POT PASSED'}).eq('id',current.id);await sb.from('tqr_bay_occupancy').update({released_at:now}).eq('unit_id',current.id).eq('section','LV').is('released_at',null);await history('PASS','LV + HI-POT','PASS');reloadUnit()}
window.startHV=async()=>{let b=await chooseCore('HV');if(!b)return;let now=nowIso(),{error}=await sb.from('tqr_bay_occupancy').insert({bay_id:b.id,section:'HV',unit_id:current.id});if(error)return toast(error.message);await sb.from('tqr_stage_state').update({hv_started:true,hv_started_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HV IN PROGRESS'}).eq('id',current.id);await history('START','HV','IN_PROGRESS');reloadUnit()}
window.hvPass=async()=>{let now=nowIso();await sb.from('tqr_stage_state').update({hv_passed:true,hv_passed_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'HV PASSED'}).eq('id',current.id);await history('PASS','HV','PASS');reloadUnit()}

async function getTimers(){let defaults={core_heatrun_seconds:120,booster_heatrun_seconds:60,sts_heatrun_seconds:120};let {data,error}=await sb.from('tqr_settings').select('setting_key,setting_value');if(error)return defaults;(data||[]).forEach(r=>{if(r.setting_key in defaults)defaults[r.setting_key]=Number(r.setting_value)||defaults[r.setting_key]});return defaults}
function durationFor(k,u,t){if(k==='core')return u.ups_type==='STS'?t.sts_heatrun_seconds:t.core_heatrun_seconds;return t.booster_heatrun_seconds}
window.heatStart=async k=>{let now=nowIso(),o={};o[k+'_started']=true;o[k+'_started_at']=now;await sb.from('tqr_stage_state').update(o).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:(k==='core'?(current.ups_type==='STS'?'STS':'CORE'):k.replaceAll('_',' ').toUpperCase())+' HEATRUN'}).eq('id',current.id);await history('START',k.toUpperCase()+' HEATRUN','IN_PROGRESS');toast('Heatrun timer started');reloadUnit()}
async function startTimerUi(u,s){let timers=await getTimers();const tick=()=>{document.querySelectorAll('.timerbox').forEach(box=>{let k=box.dataset.timer,start=s[k+'_started_at'];if(!start)return;let dur=durationFor(k,u,timers),elapsed=Math.floor((Date.now()-new Date(start).getTime())/1000),left=Math.max(0,dur-elapsed),mm=String(Math.floor(left/60)).padStart(2,'0'),ss=String(left%60).padStart(2,'0'),read=box.querySelector('.timer-readout'),btn=box.querySelector('.timer-pass');if(left>0){read.textContent=`Remaining ${mm}:${ss}`;btn.disabled=true;btn.textContent='Timer running…'}else{read.textContent='Timer Complete — Check UPS';btn.disabled=false;btn.textContent='Check UPS & Mark Passed'}})};tick();timerTicker=setInterval(tick,1000)}
window.heatPass=async k=>{let s=st(current)||{},timers=await getTimers(),start=s[k+'_started_at'];if(!start)return toast('Timer not started');let dur=durationFor(k,current,timers);if(Date.now()-new Date(start).getTime()<dur*1000)return toast('Timer is still running');if(!confirm('Timer complete. UPS checked? Mark as PASSED?'))return;let now=nowIso(),o={};o[k+'_passed']=true;o[k+'_passed_at']=now;await sb.from('tqr_stage_state').update(o).eq('unit_id',current.id);await history('PASS',k.toUpperCase()+' HEATRUN','PASS');reloadUnit()}
window.params=async()=>{let now=nowIso();await sb.from('tqr_stage_state').update({parameters_480v_saved:true,parameters_480v_saved_at:now}).eq('unit_id',current.id);await sb.from('tqr_units').update({current_stage:'480V / PARAMETERS SAVED'}).eq('id',current.id);await history('PASS','480V / PARAMETERS SAVE','PASS');reloadUnit()}
async function readyButtons(){let {data}=await sb.rpc('tqr_ready_for_exit',{p_unit_id:current.id});let a=$('#finish'),b=$('#stockbtn');if(a)a.disabled=!data;if(b)b.disabled=!data}
window.exitUnit=async status=>{let {data:ok}=await sb.rpc('tqr_ready_for_exit',{p_unit_id:current.id});if(!ok)return toast('All mandatory stages must PASS first');let now=nowIso();await sb.from('tqr_bay_occupancy').update({released_at:now}).eq('unit_id',current.id).is('released_at',null);let patch=status==='COMPLETED'?{status,current_stage:'TO FINISHING / COMPLETED',completed_at:now}:{status,current_stage:'INTERNAL STOCK',stock_at:now};await sb.from('tqr_units').update(patch).eq('id',current.id);await history('EXIT',status==='COMPLETED'?'TO FINISHING':'STOCK TRANSFER','PASS');toast(status==='COMPLETED'?'Completed — KPI updated':'Moved to internal stock');reloadUnit()}

async function loadActive(){let {data:u}=await sb.from('tqr_units').select('*').eq('status','UNDER_TESTING').order('testing_started_at',{ascending:false});$('#activelist').innerHTML=u?.length?'<table class="active-table"><tr><th>Serial</th><th>Type</th><th>Current Stage</th><th>Started</th></tr>'+u.map(x=>`<tr><td><button class="linkbtn" onclick="openFromList(\''+x.qr_code.replaceAll("'","")+'\')"><b>'+esc(x.serial_number||'—')+'</b></button></td><td>'+x.ups_type+'</td><td>'+esc(x.current_stage||'UNDER TESTING')+'</td><td>'+(x.testing_started_at?new Date(x.testing_started_at).toLocaleString():'—')+'</td></tr>').join('')+'</table>':'<div class="placeholder-card">No UPS currently under testing.</div>'}
window.openFromList=q=>{$('#qr').value=q;document.querySelector('nav button[data-page="scan"]').click();openQR()}
async function loadStock(){let {data:u}=await sb.from('tqr_units').select('*').eq('status','STOCK').order('stock_at');$('#stocklist').innerHTML=u?.length?'<table><tr><th>Serial</th><th>Type</th><th>Stock Since</th><th></th></tr>'+u.map(x=>`<tr><td>${esc(x.serial_number)}</td><td>${x.ups_type}</td><td>${new Date(x.stock_at).toLocaleString()}</td><td><button class="pass" onclick="stockFinish('${x.id}')">TO FINISHING</button></td></tr>`).join('')+'</table>':'<p>No UPS in internal stock.</p>'}
window.stockFinish=async id=>{let now=nowIso();await sb.from('tqr_units').update({status:'COMPLETED',current_stage:'TO FINISHING / COMPLETED',completed_at:now}).eq('id',id);await sb.from('tqr_stage_history').insert({unit_id:id,action:'EXIT',stage:'TO FINISHING FROM STOCK',result:'PASS'});toast('Released from stock — KPI updated');loadStock();refresh()}

function generateQrBatch(){let qty=Math.max(1,Math.min(100,Number($('#qrQty').value)||1)),stamp=new Date().toISOString().replace(/\D/g,'').slice(0,14),batch=$('#qrBatch');batch.innerHTML='';for(let i=1;i<=qty;i++){let code=`TQR-${stamp}-${String(i).padStart(3,'0')}`,card=document.createElement('div');card.className='qr-card';card.innerHTML=`<div class="qr-canvas"></div><b>${code}</b>`;batch.appendChild(card);new QRCode(card.querySelector('.qr-canvas'),{text:code,width:150,height:150,correctLevel:QRCode.CorrectLevel.M})}$('#qrBatchInfo').textContent=`Generated ${qty} embedded QR code(s). These are not received into tracking until first scan.`}

async function loadTimers(){let t=await getTimers();$('#timerCore').value=t.core_heatrun_seconds;$('#timerBooster').value=t.booster_heatrun_seconds;$('#timerSts').value=t.sts_heatrun_seconds;$('#timerStatus').textContent='Current shared pilot timer values loaded.'}
async function saveTimers(){let vals={core_heatrun_seconds:Number($('#timerCore').value),booster_heatrun_seconds:Number($('#timerBooster').value),sts_heatrun_seconds:Number($('#timerSts').value)};if(Object.values(vals).some(v=>!Number.isFinite(v)||v<5))return toast('Minimum timer is 5 seconds');let rows=Object.entries(vals).map(([setting_key,setting_value])=>({setting_key,setting_value}));let {error}=await sb.from('tqr_settings').upsert(rows,{onConflict:'setting_key'});if(error)return toast(error.message);$('#timerStatus').textContent='Saved — all pilot devices will use these timer values.';toast('Pilot timers saved')}

sb.channel('tqr-live').on('postgres_changes',{event:'*',schema:'public',table:'tqr_units'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'tqr_bay_occupancy'},refresh).subscribe();refresh();
