
mountTopbar('reports');let data,historical=[];
async function planned(){const r=await sb.from('tqr_settings').select('*').eq('setting_key','planned_receipt_per_day').maybeSingle();return Number(r.data?.setting_value)||0}
function daily(month,type){const [Y,M]=month.split('-').map(Number),days=new Date(Y,M,0).getDate(),a=Array(days).fill(0);data.u.filter(u=>monthOf(u.received_at)===month&&(type==='CORE'?(u.ups_type==='3X'||u.ups_type==='2X'):u.ups_type===type)).forEach(u=>a[Number(u.received_at.slice(8,10))-1]++);return a}
function draw(canvas,ser,plan=0){const dpr=devicePixelRatio||1,W=Math.max(760,canvas.clientWidth)*dpr,H=280*dpr,L=50*dpr,R=18*dpr,T=28*dpr,B=36*dpr,days=ser[0].data.length,max=Math.max(5,plan,...ser.flatMap(s=>s.data)),c=canvas.getContext('2d');canvas.width=W;canvas.height=H;c.clearRect(0,0,W,H);c.fillStyle='#061827';c.fillRect(0,0,W,H);c.strokeStyle='#174660';for(let y=0;y<=max;y++){let py=T+(H-T-B)*(1-y/max);c.beginPath();c.moveTo(L,py);c.lineTo(W-R,py);c.stroke();c.fillStyle='#8fc4e2';c.font=`${10*dpr}px Arial`;c.fillText(String(y),12*dpr,py+3*dpr)}const X=i=>L+i/(days-1)*(W-L-R),Y=v=>T+(H-T-B)*(1-v/max),cols=['#20d8ff','#1fe58f'];if(plan){c.setLineDash([8*dpr,6*dpr]);c.strokeStyle='#49b9ff';c.lineWidth=2*dpr;c.beginPath();for(let i=0;i<days;i++){i?c.lineTo(X(i),Y(plan)):c.moveTo(X(i),Y(plan))}c.stroke();c.setLineDash([])}ser.forEach((s,j)=>{c.strokeStyle=cols[j%cols.length];c.lineWidth=2.8*dpr;c.beginPath();s.data.forEach((v,i)=>i?c.lineTo(X(i),Y(v)):c.moveTo(X(i),Y(v)));c.stroke();s.data.forEach((v,i)=>{c.beginPath();c.fillStyle=cols[j%cols.length];c.arc(X(i),Y(v),3*dpr,0,Math.PI*2);c.fill()});c.fillStyle=cols[j%cols.length];c.fillText(s.name,L+j*90*dpr,14*dpr)});c.fillStyle='#8fc4e2';let step=Math.ceil(days/15);for(let i=0;i<days;i+=step)c.fillText(String(i+1),X(i)-3*dpr,H-10*dpr)}
function matrix(month,plan){const [Y,M]=month.split('-').map(Number),days=new Date(Y,M,0).getDate(),c3=daily(month,'3X'),c2=daily(month,'2X'),sts=daily(month,'STS');const dates=Array.from({length:days},(_,i)=>String(i+1).padStart(2,'0')+'-'+new Date(Y,M-1).toLocaleString('en',{month:'short'}));const row=(name,vals,cls='')=>`<tr class="${cls}"><th>${name}</th>${vals.map(v=>`<td>${v}</td>`).join('')}</tr>`;const core=c3.map((v,i)=>v+c2[i]),total=core.map((v,i)=>v+sts[i]),gap=total.map(v=>v-plan);$('#dailyMatrix').innerHTML=`<tr><th>Date</th>${dates.map(d=>`<th>${d}</th>`).join('')}</tr>${row('Ideal Capacity',Array(days).fill(plan))}${row('3X Received',c3)}${row('2X Received',c2)}${row('STS Received',sts)}${row('Total Received',total)}${row('GAP',gap,'gap-row')}`;const received=total.reduce((a,b)=>a+b,0),ideal=plan*days,met=total.filter(v=>v>=plan).length;$('#summaryCards').innerHTML=[['MONTHLY IDEAL CAPACITY',ideal],['RECEIVED FOR TESTING',received],['NET GAP',received-ideal],['DAYS MET TARGET',met]].map(x=>`<div class="summary-card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function renderHistory(){const y=Number($('#historyYear').value),months=Array.from({length:12},(_,i)=>`${y}-${String(i+1).padStart(2,'0')}`);$('#historySummary').innerHTML=months.map(m=>{const rows=historical.filter(x=>monthOf(x.month_start)===m),g=Object.fromEntries(rows.map(x=>[x.ups_type,x])),fmt=t=>{const x=g[t]||{};return `${x.target||0}/${x.received||0}/${x.completed||0}`},tot=['3X','2X','STS'].reduce((a,t)=>a+(g[t]?.completed||0),0);return `<tr><td>${new Date(m+'-01').toLocaleString('en',{month:'short'})}</td><td>${fmt('3X')}</td><td>${fmt('2X')}</td><td>${fmt('STS')}</td><td>${tot}</td><td>${esc(rows[0]?.notes||'')}</td></tr>`}).join('')}
async function render(){data=await loadCore();const hr=await sb.from('tqr_historical_months').select('*').order('month_start');historical=hr.data||[];const m=$('#reportMonth').value||ym(),p=await planned();draw($('#chartCore'),[{name:'3X + 2X',data:daily(m,'CORE')}],p);draw($('#chartSts'),[{name:'STS',data:daily(m,'STS')}],0);matrix(m,p);const years=[...new Set([new Date().getFullYear(),...historical.map(x=>Number(x.month_start.slice(0,4)))])].sort((a,b)=>b-a);$('#historyYear').innerHTML=years.map(y=>`<option>${y}</option>`).join('');renderHistory()}
$('#reportMonth').value=ym();$('#reportMonth').onchange=render;$('#historyYear').onchange=renderHistory;$('#copyTable').onclick=async()=>{try{await navigator.clipboard.writeText($('#dailyMatrix').innerText);showToast('Table copied')}catch{showToast('Copy blocked by browser')}};render().catch(e=>showToast(e.message));window.addEventListener('resize',()=>data&&render());
